.Dd 2021-12-12
.Dt HK 1
.Os
.Sh NAME
.Nm hk
.Nd Set temporary X11 hotkeys
.Sh SYNOPSIS
.Nm hk
.Op Fl w
.Ar hotkey
.Ar command Op Ar argument ...
.Sh DESCRIPTION
.Nm
allows temporary X11 hotkeys to be set. For example:
.Bd -literal -offset 4n
hk Ctrl+Shift+F6 notify-send Hello
.Ed
.Pp
will execute the command
.Dq notify-send Hello
when
.Dq Ctrl+Shift+F6
is pressed.
.Nm
exits as soon as the command has executed.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl w
causes
.Nm
to wait until
.Em all
keys (not just the hotkey) are released before executing
.Em command .
.It hotkey
Is the hotkey to active the execution of
.Em command .
Hotkeys take the form:
.Bd -literal -offset 4n
[Modifier1[+Modifier2[+...]]+]<Key>
.Ed
.Pp
The particular modifiers available depend on XKB's interpretation of your
physical keyboard, but typically include
.Em Ctrl
/
.Em Control,
.Em Shift,
and so on. Modifiers are case insensitive.
.Em key
is case sensitive and again depends on
.Em XKB 's
interpretation of your physical keyboard. If in doubt,
.Xr xev 1
can be used to find out the
.Em XKB
name of a physical key.
.It command Op Ar arguments ...
is the program to be executed, using the outer shell's normal lookup mechanism
to locate
.Em command .
.Nm
passes stdin, stdout, and stderr unchanged to
.Em command .
.El
.Sh CAVEATS
.Nm
ignores the Caps Lock and Num Lock modifiers when determining if
.Em hotkey
has been pressed, but other keyboard modifiers (which you may or may not be
aware of!) can prevent
.Em hotkey
being triggered.
.Sh SEE ALSO
.Xr xev 1
.Pp
.Lk https://tratt.net/laurie/src/hk/
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Laurence Tratt Aq https://tratt.net/laurie/
